"use strict";
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
let subject;try{subject=require('./build-provenance.cjs');}catch(error){if(error.code!=='MODULE_NOT_FOUND')throw error;}
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'radar-build-proof-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));fs.mkdirSync(path.join(root,'src'));fs.mkdirSync(path.join(root,'dist'));fs.writeFileSync(path.join(root,'package.json'),' {"version":"1.5.2"}');fs.writeFileSync(path.join(root,'src/main.ts'),'input');fs.writeFileSync(path.join(root,'dist/index.html'),'output');return root;}
test('build hooks bind actual start inputs to completed renderer output',t=>{assert.equal(typeof subject?.createBuildProvenancePlugin,'function');const root=fixture(t),plugin=subject.createBuildProvenancePlugin({root,kind:'web'});plugin.buildStart();plugin.buildEnd();plugin.closeBundle();const receipt=JSON.parse(fs.readFileSync(path.join(root,'dist/build-provenance.json'),'utf8'));assert.equal(receipt.kind,'web');assert.equal(receipt.status,'passed');assert.equal(receipt.sourceHashes['src/main.ts'],require('node:crypto').createHash('sha256').update('input').digest('hex'));assert.equal(receipt.outputHashes['index.html'],require('node:crypto').createHash('sha256').update('output').digest('hex'));});
test('source edits during a build and failed builds never retain a success receipt',t=>{assert.equal(typeof subject?.createBuildProvenancePlugin,'function');const root=fixture(t),receipt=path.join(root,'dist/build-provenance.json');fs.writeFileSync(receipt,'old success');const plugin=subject.createBuildProvenancePlugin({root,kind:'web'});plugin.buildStart();assert.equal(fs.existsSync(receipt),false);fs.writeFileSync(path.join(root,'src/main.ts'),'changed');plugin.buildEnd();assert.throws(()=>plugin.closeBundle(),/inputs changed/);assert.equal(fs.existsSync(receipt),false);const failed=subject.createBuildProvenancePlugin({root,kind:'web'});failed.buildStart();failed.buildEnd(Error('compile failed'));failed.closeBundle();assert.equal(fs.existsSync(receipt),false);});
test('source manifests cover asset/icon contents and reject symlink inputs',t=>{assert.equal(typeof subject?.snapshotBuildInputs,'function');const root=fixture(t);fs.mkdirSync(path.join(root,'assets'));fs.writeFileSync(path.join(root,'assets/icon.svg'),'first');fs.writeFileSync(path.join(root,'root-icon.png'),'first');const first=subject.snapshotBuildInputs(root);fs.writeFileSync(path.join(root,'assets/icon.svg'),'second');fs.writeFileSync(path.join(root,'root-icon.png'),'second');const second=subject.snapshotBuildInputs(root);assert.notEqual(first['assets/icon.svg'],second['assets/icon.svg']);assert.notEqual(first['root-icon.png'],second['root-icon.png']);fs.symlinkSync('../package.json',path.join(root,'src/linked.json'));assert.throws(()=>subject.snapshotBuildInputs(root),/symlink/);});

for(const kind of ['web','review'])test(`output root symlink cannot delete or overwrite outside receipt: ${kind}`,t=>{
 const root=fixture(t),external=fs.mkdtempSync(path.join(os.tmpdir(),'radar-outside-proof-'));t.after(()=>fs.rmSync(external,{recursive:true,force:true}));const managed=path.join(root,kind==='web'?'dist':'dist/review');fs.rmSync(managed,{recursive:true,force:true});fs.symlinkSync(external,managed,'junction');const sentinel=path.join(external,'build-provenance.json');fs.writeFileSync(sentinel,'KEEP OUTSIDE');const plugin=subject.createBuildProvenancePlugin({root,kind});assert.throws(()=>plugin.buildStart(),/symlink|unsafe/i);assert.equal(fs.readFileSync(sentinel,'utf8'),'KEEP OUTSIDE');
});
